### ISSUE TITLE
Problem pri pouziti realnych dat

### ISSUE THREAD

**Issue by ludekbartek** [Sachji/ODSKartW#6]
Pokud pouziji realna data, ktera mam, tak aplikace pri zobrazeni sheetu pada s NullPointerException. Odlisnosti jsou nadpisi sloupcu, pouze nektera media maji obsazeny vsechny tituly.

**Comment by ghost** [comment]
@ludekbartek Je potřeba si uvědomit, že aplikace není stavěná pro libovolný uživatelský soubor vygenerovaný nějakým tabulkovým editorem. Stává se velmi často, že editor uloží něco, co na první pohled není vidět, nicméně narušuje logiku, s jakou by měla být data načítána a reprezentována. Dále soubor slouží v podstatě jako databáze, je jeden a napevno uložený v aplikaci pro jeho manipulaci s ním. Ani u databáze nelze předpokládat, že si někdo vloží svou vlastní databázi, protože může obsahovat trochu odlišené parametry.
Pro vyzkoušení aplikace doporučuji využít soubor, který je součástí repozitáře a který je naprosto korektní z hlediska struktury dat.
